name: Build template

on:
  workflow_call:
    inputs:
      method:
        description: "Method to test"
        required: true
        type: string

env:
  DOCKER_BUILDKIT: 0

jobs:
  build_template_x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cp3-bench . --build-arg METHODS=${{ inputs.method }}

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: cp3-bench
          run: python3 -m unittest tests/utils/test_build.py

  build_template_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install docker
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install --cask docker
          docker --version
          docker build -t cp3-bench . --build-arg METHODS=${{ inputs.method }}

      - name: Open Docker
        run: open /Apllications/Docker.app

      - name: Build Docker image
        run: docker build -t cp3-bench . --build-arg METHODS=${{ inputs.method }}

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: cp3-bench
          run: python3 -m unittest tests/utils/test_build.py
