name: Build test

# on:
#   workflow_run:
#     workflows: ["Python test"]
#     types:
#       - completed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

env:
  DOCKER_BUILDKIT: 0

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and docker build
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cp3-bench
      
      - name: Run tests
        run: docker run -it cp3-bench python -m unittest tests/utils/test_build.py