name: Build test

# on:
#   workflow_run:
#     workflows: ["Python test"]
#     types:
#       - completed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and docker build
        uses: actions/checkout@v3
      
      - name: Build docker iamge
        run: docker build -t cp3-bench .
      
      - namw: Run docker container
        run: docker run cp3-bench python -m unittest tests/utitls/test_build.py