name: Build test

# on:
#   workflow_run:
#     workflows: ["Python test"]
#     types:
#       - completed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

env:
  DOCKER_BUILDKIT: 0

jobs:
  build_test_method:
    runs-on: ubuntu-latest
    outputs:
      method: ${{ steps.set_method.outputs.method }}
    steps:
      - name: Set method
        id: set_method
        run: echo "value=[\"aifeynman\"]" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.set_method.outputs.method }}"

  build_test:
    needs: build_test_method
    runs-on: ubuntu-latest
    strategy:
      matrix:
        method: ${{fromJson(needs.build_test_method.outputs.method)}}
    uses: ./.github/workflows/build-template.yml
    name: Build test
    with:
      method: ${{ matrix.method }}