name: Build test

# on:
#   workflow_run:
#     workflows: ["Python test"]
#     types:
#       - completed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and docker build
        uses: actions/checkout@v3
      
      - name: QEMU setup
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: "Dockerfile"
          tags: cp3-bench
          platforms: linux/amd64,linux/arm64
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: cp3-bench
          run: python -m unittest tests/utils/test_build.py