name: Build test

# on:
#   workflow_run:
#     workflows: ["Python test"]
#     types:
#       - completed

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "**"

jobs:
  build_set_method:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Set method
        id: matrix
        run: echo "value=[\"aifeynman\", \"dsr\"]" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.matrix.outputs.value }}"

  build_test:
    needs: build_set_method
    strategy:
      matrix:
        value: ${{fromJSON(needs.build_set_method.outputs.matrix)}}
    uses: ./.github/workflows/build-template.yml
    name: Build test
    with:
      method: ${{ matrix.value }}