name: Build template

on:
  workflow_call:
    inputs:
      method:
        description: "Method to test"
        required: true
        type: string


jobs:
  build_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and docker build
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t cp3-bench . --build-arg METHODS=${{ inputs.method }}

      - name: Run tests
        run: docker run -it cp3-bench python -m unittest tests/utils/test_build.py